### ISSUE TITLE
Won't build on Solus

### ISSUE THREAD

**Issue by junocomp** [danielpinto8zz6/budgie-network-applet#1]
Missing a few dependencies, can't build. Specially gtk+-3.0.

**Comment by danielpinto8zz6** [comment]
you have budgie installed and you don't have gtk3?

**Comment by junocomp** [comment]
I sorted out, this are the missing dependencies in Solus. You should post this on the ReadMe page.

sudo eopkg install budgie-desktop-devel libgtk-3-devel ninja gobject-introspection meson vala network-manager-applet-devel libgee-devel

By the way, it works great!

**Comment by danielpinto8zz6** [comment]
thanks
