### ISSUE TITLE
Adding the applet to a vertical panel affects its padding

### ISSUE THREAD

**Issue by plafue** [danielpinto8zz6/budgie-network-applet#10]
Adding this applet to a vertical panel messes with the padding at the `Start` and `End` sections of the panel.

![budgie-network-applet](https://user-images.githubusercontent.com/1915763/80999582-33226080-8e45-11ea-99bb-aefb318c5a39.gif)

I'm using the package `budgie-network-manager-applet` version `1.0.1-2` from ubuntu's focal fossa repositories.

**Comment by danielpinto8zz6** [comment]
The current version is 2.2, can you try with a more updated version?

**Comment by plafue** [comment]
Thanks for the reply, @danielpinto8zz6 . I just compiled tag `2.2` (fb6fe41)and replaced the version installed by the package manager... with the same results
![image](https://user-images.githubusercontent.com/1915763/81483160-3dc16900-923c-11ea-8d97-fb6283e5eb73.png)

**Comment by danielpinto8zz6** [comment]
Does it happen with other applets than clock? And with other applets than network?

**Comment by plafue** [comment]
It happens only with network manager applet, on its own or in combination with any other applet.

![budgie-network-applet-2](https://user-images.githubusercontent.com/1915763/81491421-c23cd780-928e-11ea-881d-1ea5709e4a71.gif)
