### ISSUE TITLE
Adding icons to header widgets

### ISSUE THREAD

**Issue by EbonJaeger** [danielpinto8zz6/budgie-network-applet#3]
I was thinking that it might look nice if icons were added before each connection type name (as in, before Wired, WiFi, etc) on the switches, similar to DataDrake's mockup (I'd include a link to that, but I'm not sure where it is). See https://i.imgur.com/MiBu57L.png for my own terrible picture explanation.

I started a branch for this, but so far it hasn't worked like I expected. I'm more than willing to continue work on it if desired.

**Comment by danielpinto8zz6** [comment]
Hey, when you have the mockup send me the link :D

**Comment by EbonJaeger** [comment]
Here's the Glade file he created: https://dev.getsol.us/source/budgie-network-applet/browse/master/network-applet.glade

It ended up something like this, though: https://0x0.st/sIfU.png

Either way, that should give a nice indication.

**Comment by danielpinto8zz6** [comment]
looks nice, make pr

**Comment by EbonJaeger** [comment]
Cool. Will, once I figure out why the icons don't show as I'd expect them to.
