### ISSUE TITLE
Keeps opening google.com

### ISSUE THREAD

**Issue by marc0tjevp** [danielpinto8zz6/budgie-network-applet#4]
After enabling the applet Firefox opens going to google.com (not my homepage). Disabling it again fixes the issue. It sometimes happens in the background, but also happens when switching networks.

**Comment by danielpinto8zz6** [comment]
yes, fixed here: https://github.com/danielpinto8zz6/budgie-network-applet/commit/9ece72ad9d542c15179146630ca3ea8ac505b0be
Try installing again
