### ISSUE TITLE
Weird color when i click to connect to a wifi

### ISSUE THREAD

**Issue by AXeL-dev** [danielpinto8zz6/budgie-network-applet#9]
Hey, thanks for the great applet!

I noticed that i have a little color issue when i click to connect to a wifi, if i select the wifi by myself the color turns to white
![Capture d'écran 2019-03-16 18:05:46](https://user-images.githubusercontent.com/30635693/54478826-66073080-480e-11e9-86ea-2e47cf99b602.png)

On a dark theme everything seems good
![Capture d'écran 2019-03-16 18:06:13](https://user-images.githubusercontent.com/30635693/54478857-bbdbd880-480e-11e9-83b0-943a00ed6bc9.png)

OS: Ubuntu budgie 18.04
Theme: [McMojave](https://www.gnome-look.org/p/1275087/)

I tried on different white themes & the issue is the same.

Thanks for your help x)

**Comment by danielpinto8zz6** [comment]
Hi,
This is a theme problem
